export const tours = [
  {
    id: 1,
    name: "Malaga Bike Tours",
    href: "#",
    imageSrc: "https://cdn.biketours.com/assets/files/2820/adobestock_267990467.1600x500.jpeg.webp",
    imageAlt: "Bike Tour Image.",
    price: "$25",
    hours: "3 Hours",
    languages: ["English", "Spanish", "French"],
    overview:
      "Bike tours in Malaga are always cool. Is there a better way to discover Malaga than with a bike? To cruise past the ancient Roman ruins and historic cathedrals? To enjoy the sea view, the wind, and the sun on the pristine beaches? Discover the capital of the Costa del Sol with our Malaga Bike Tours. You will uncover the best parts of this truly breathtaking city with a helpful, friendly tour guide. We will also have the chance to meet other like-minded explorers like yourself. So, what are you waiting for?",
    location: "Malaga, Spain",
    time: "10:00 AM - 1:00 PM",
    rating: 4.7,
    reviews: [
      {
        title: "Amazing Experience!",
        rating: 4,
        author: "John Doe",
        date: "2024-05-12",
        text: "Loved every part of the tour. The guide was knowledgeable and friendly.",
      },
      {
        title: "Great way to see the city",
        rating: 4,
        author: "Jane Smith",
        date: "2024-04-22",
        text: "Had a fantastic time, but it was a bit too hot for cycling.",
      },
    ],
  },
  {
    id: 2,
    name: "Malaga Boat Trip",
    href: "#",
    imageSrc: "https://south.tours/wp-content/uploads/2023/02/barco-catamaran-malaga_11zon.jpg",
    imageAlt: "Barcelona Architecture Tour Image.",
    price: "$30",
    hours: "4 Hours",
    languages: ["English", "Spanish", "German"],
    overview:
      "Are you planning a visit to Malaga and looking for a rewarding experience on Malaga’s coastlines? Then come and join us on Malaga Boat Trip for the perfect blend of relaxation, adventure, and splendid views. Whether you are a nature enthusiast, a photography lover, or simply seeking a peaceful escape, our boat trip will ensure your comfort and enjoyment throughout the journey.",
    location: "Malaga, Spain",
    time: "9:00 AM - 1:00 PM",
    rating: 4.8,
    reviews: [
      {
        title: "Fascinating tour",
        rating: 5,
        author: "Alice Green",
        date: "2024-06-14",
        text: "A must-do for architecture lovers. The guide was superb!",
      },
      {
        title: "Highly recommend",
        rating: 3,
        author: "Bob Brown",
        date: "2024-05-30",
        text: "Very informative and well-organized tour.",
      },
    ],
  },
  {
    id: 3,
    name: "Malaga Tapas Tour",
    href: "#",
    imageSrc: "https://i.pinimg.com/originals/96/f0/85/96f085a6515d6924fdf8598f383fed41.jpg",
    imageAlt: "Madrid Walking Tour Image.",
    price: "$20",
    hours: "2 Hours",
    languages: ["English", "Spanish"],
    overview:
      "At the Malaga Tapas Tour, you will taste a selection of local tapas dishes and the best wine selections to pair with. A local tour guide who’s an expert on the food and local wine of the region will accompany you during this Malaga Food Tour and explain the characteristics of each magnificent tapas dish you taste.",
    location: "Malaga, Spain",
    time: "11:00 AM - 1:00 PM",
    rating: 4.6,
    reviews: [
      {
        title: "Great tour",
        rating: 3,
        author: "Carlos Ruiz",
        date: "2024-07-01",
        text: "Perfect way to learn about Madrid's history. Highly recommended.",
      },
      {
        title: "Informative but crowded",
        rating: 3,
        author: "Diana Prince",
        date: "2024-06-20",
        text: "Loved the content, but there were too many people on the tour.",
      },
    ],
  },
  {
    id: 4,
    name: "Malaga Pub Crawl",
    href: "#",
    imageSrc: "https://south.tours/wp-content/uploads/2019/10/malaga-pub-crawl-nightlife.jpg.webp",
    imageAlt: "Seville Flamenco Show Image.",
    price: "$40",
    hours: "1.5 Hours",
    languages: ["English", "Spanish"],
    overview:
      "Malaga nightlife is a unique experience when traveling to Spain! Joining our Malaga pub crawl (also known as the Malaga nightlife tour) guarantees a 100% fun and enjoyable experience!",
    location: "Malaga, Spain",
    time: "8:00 PM - 9:30 PM",
    rating: 4.9,
    reviews: [
      {
        title: "Incredible performance",
        rating: 5,
        author: "Elena Gomez",
        date: "2024-05-05",
        text: "The dancers and musicians were phenomenal. Truly unforgettable.",
      },
      {
        title: "Mesmerizing",
        rating: 5,
        author: "Michael Johnson",
        date: "2024-04-25",
        text: "A wonderful cultural experience. Loved every minute.",
      },
    ],
  },
  {
    id: 5,
    name: "Malaga Free Walking Tour",
    href: "#",
    imageSrc: "https://south.tours/wp-content/uploads/2019/10/15.png.webp",
    imageAlt: "Valencia Food Tour Image.",
    price: "$50",
    hours: "3 Hours",
    languages: ["English", "Spanish", "Italian"],
    overview:
      "These tours are led by guides who are passionate about their city and love showing it off to new people. Most of the time, they offer you advice on the best places to eat, drink and explore. When the tour is over they will kindly ask for tips, so you pay what you think the tour was worth. This “pay what you think it’s worth” model makes it possible for everyone to enjoy a fun, creative and educational walking tour. Isn’t it amazing?",
    location: "Malaga, Spain",
    time: "1:00 PM - 4:00 PM",
    rating: 4.7,
    reviews: [
      {
        title: "Delicious and fun",
        rating: 5,
        author: "Maria Fernandez",
        date: "2024-06-02",
        text: "A food lover's dream. The guide was fantastic and the food was amazing.",
      },
      {
        title: "Great variety",
        rating: 5,
        author: "Paul Martin",
        date: "2024-05-18",
        text: "Loved the variety of food and the cultural insights.",
      },
    ],
  },
  {
    id: 6,
    name: "Granada Hiking Tour",
    href: "#",
    imageSrc: "https://images.pexels.com/photos/1271619/pexels-photo-1271619.jpeg?cs=srgb&dl=pexels-andreimike-1271619.jpg&fm=jpg",
    imageAlt: "Granada Alhambra Tour Image.",
    price: "$0",
    hours: "3 Hours",
    languages: ["English", "Spanish", "French"],
    overview:
      "With this Sierra Nevada Hiking Tour, you will crawl under caves, climb, and walk through narrow pathways and hanging bridges to explore the hidden gems of the Mirador de Los Cahorros. You will have an expert local host to guide you through the whole path to ensure you don’t miss any impressive sights. They will also inform you about the historical and natural facts of the spots, and share exciting facts about the Sierra Nevada Spain and the Mirador de Los Cahorros. ",
    location: "Granada, Spain",
    time: "10:00 AM - 1:00 PM",
    rating: 4.8,
    reviews: [
      {
        title: "Breathtaking",
        rating: 4,
        author: "Laura King",
        date: "2024-07-03",
        text: "The Alhambra is a must-see. Our guide was excellent.",
      },
      {
        title: "Wonderful tour",
        rating: 4,
        author: "James Wilson",
        date: "2024-06-15",
        text: "Loved learning about the history and architecture. Highly recommend.",
      },
    ],
  },
  {
    id: 7,
    name: "Granada Tapas Tour",
    href: "#",
    imageSrc: "https://south.tours/wp-content/uploads/2021/02/tapas-2.jpg",
    imageAlt: "Bilbao Art Tour Image.",
    price: "$45",
    hours: "4 Hours",
    languages: ["English", "Spanish", "Basque"],
    overview:
      "Discover authentic Andalucian Food on our Granada Food Tour! Come on a culinary journey and experience the distinctive and exquisite flavours of Spanish cuisine. On our Granada Tapas Tour, you will have the chance to get a taste of the best of what the Granada gastronomical scene has to offer. Enjoy the best tapas in Granada, while our local tour guide will tell you all about the history and origin of true Spanish tapas. Furthermore, you will have the opportunity to take in the food while pairing it with the perfect wine. The tour guide will help you figure out what tapas and what wine will best suit your preferences. The Granada Food Tour traced down the best tapas restaurants in Granada, so you do not have to. In these carefully selected tapas bars, you will have the opportunity to enjoy the best tapas in town. What are you waiting for? Join the Granada Tapas Tour and experience authentic Spanish cuisine with local Tapas and wine!",
    location: "Granada, Spain",
    time: "2:00 PM - 6:00 PM",
    rating: 4.7,
    reviews: [
      {
        title: "Art lover's paradise",
        rating: 4,
        author: "Patricia Lee",
        date: "2024-05-28",
        text: "Amazing tour with lots of insights into local art and culture.",
      },
      {
        title: "Very informative",
        rating: 2,
        author: "Samuel Harris",
        date: "2024-04-30",
        text: "Great guide and wonderful art collections. Thoroughly enjoyed it.",
      },
    ],
  },
  {
    id: 8,
    name: "Granada Pub Crawl",
    href: "#",
    imageSrc: "https://south.tours/wp-content/uploads/2022/10/granada-pub-crawl.webp",
    imageAlt: "Mallorca Beach Tour Image.",
    price: "$35",
    hours: "5 Hours",
    languages: ["English", "Spanish"],
    overview:
      "Do you want to experience the unique nightlife of Granada? Then come and join us for a fun and unforgettable night at our Granada Pub Crawl! We guarantee you an amazing night with lovely people, free drinks and cool bars in Granada. Are you looking for things to do in Granada at night? Join our Granada Nightlife Tour to create incredible memories that will last a lifetime!",
    location: "Granada, Spain",
    time: "10:00 AM - 3:00 PM",
    rating: 4.9,
    reviews: [
      {
        title: "Paradise on Earth",
        rating: 5,
        author: "Olivia Young",
        date: "2024-06-10",
        text: "The beaches were beautiful and the tour was well-organized. Perfect day out.",
      },
      {
        title: "Loved it!",
        rating: 3,
        author: "Henry Adams",
        date: "2024-05-22",
        text: "Great way to experience Mallorca's beaches. Highly recommend.",
      },
    ],
  },
];
